export const copy = {
  meta: {
    title: "Tian & Omy Wedding Invitation",
    description: "Undangan pernikahan Tian & Omy",
  },
  cover: {
    kicker: "The Wedding Of",
    to: "Kepada Yth.",
    defaultGuest: "Bapak/Ibu/Saudara/i",
    openButton: "Buka Undangan",
  },
  hero: {
    kicker: "Save The Date",
    quote:
      "“Anak-anakku, marilah kita mengasihi bukan dengan perkataan atau dengan lidah, tetapi dengan perbuatan dan dalam kebenaran.”",
    quoteSource: "1 Yohanes 3:18",
  },
  couple: {
    groomLabel: "The Groom",
    brideLabel: "The Bride",
  },
  event: {
    title: "Waktu & Tempat",
    subtitle: "Dengan penuh sukacita, kami mengundang Anda untuk turut merayakan hari bahagia kami",
    countdownTitle: "Menuju Hari Bahagia",
    days: "Hari",
    hours: "Jam",
    minutes: "Menit",
    seconds: "Detik",
    mapButton: "Lihat Lokasi",
  },
  gallery: {
    title: "Galeri",
    subtitle: "Sepenggal cerita kami",
  },
  rsvp: {
    title: "Pesan & Doa Restu",
    subtitle: "Doa, harapan, dan ucapan terbaik dari Anda akan menjadi kenangan berharga yang senantiasa kami simpan dalam perjalanan baru kami",
    nameLabel: "Nama Tamu",
    namePlaceholder: "Nama Tamu",
    attendanceLabel: "Konfirmasi Kehadiran",
    attendanceYes: "Hadir",
    attendanceNo: "Tidak Hadir",
    attendanceMaybe: "Masih Ragu",
    messageLabel: "Doa & Ucapan",
    messagePlaceholder: "Sampaikan doa, harapan dan ucapan terbaik untuk kami",
    submitButton: "Kirim Ucapan",
    submittingButton: "Mengirim...",
    successTitle: "Terima kasih!",
    successMessage: "Konfirmasi dan ucapan Anda telah kami terima.",
    resetButton: "Kirim Tanggapan Lain",
    errorMessage: "Maaf, terjadi kesalahan. Silakan coba lagi.",
    notConfiguredMessage: "Formulir RSVP belum aktif. Silakan coba lagi nanti.",
  },
  wishes: {
    title: "Ucapan Tamu",
    loadingMessage: "Memuat ucapan...",
    emptyMessage: "Belum ada ucapan. Jadilah yang pertama mengirimkan doa restu!",
    errorMessage: "Gagal memuat ucapan.",
    prevButton: "Sebelumnya",
    nextButton: "Berikutnya",
  },
  gift: {
    title: "Wedding Gift",
    subtitle: "Kehadiran dan doa restu Anda sudah menjadi hadiah yang sangat berharga bagi kami. Apabila berkenan berbagi tanda kasih, informasi hadiah digital tersedia melalui tombol berikut.",
    accountNumberLabel: "Nomor Rekening",
    copyButton: "Salin",
    copiedButton: "Tersalin",
  },
  footer: {
    closing: "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.",
    thankYou: "Terima kasih atas doa restu Anda.",
    signature: "Kami yang berbahagia,",
  },
};
