export const copyV2 = {
  nav: {
    home: "Home",
    couple: "Groom & Bride",
    event: "Event Details",
    rsvp: "RSVP",
    wishes: "Wishes",
    gallery: "Gallery",
    gift: "Wedding Gift",
  },
  cover: {
    kicker: "The Wedding Of",
    to: "Yth. Bapak/Ibu/Saudara/i:",
    defaultGuest: "Bapak/Ibu/Saudara/i",
    disclaimer: "Mohon maaf apabila terdapat kesalahan penulisan nama dan gelar.",
    openButton: "Buka Undangan",
  },
  home: {
    quote:
      "“Kasih itu sabar; kasih itu murah hati; ia tidak cemburu. Ia tidak memegahkan diri dan tidak sombong.”",
    quoteSource: "1 Korintus 13:4",
  },
  couple: {
    title: "Groom & Bride",
    subtitle: "Dengan penuh syukur kami persembahkan pasangan mempelai",
    groomLabel: "Groom",
    brideLabel: "Bride",
  },
  event: {
    title: "Event Details",
    subtitle: "Kami menantikan kehadiran Anda pada hari bahagia kami",
    countdownTitle: "Menuju Hari Bahagia",
    days: "Hari",
    hours: "Jam",
    minutes: "Menit",
    seconds: "Detik",
    mapButton: "Google Maps",
    calendarButton: "Add to Calendar",
  },
  rsvp: {
    title: "RSVP",
    subtitle: "Mohon konfirmasi kehadiran Anda pada hari bahagia kami",
    nameLabel: "Nama",
    namePlaceholder: "Nama lengkap Anda",
    guestCountLabel: "Jumlah Tamu",
    attendanceLabel: "Konfirmasi Kehadiran",
    attendanceYes: "Hadir",
    attendanceNo: "Tidak Hadir",
    attendanceMaybe: "Masih Ragu",
    messageLabel: "Ucapan",
    messagePlaceholder: "Tuliskan ucapan dan doa restu untuk kami...",
    submitButton: "Kirim",
    submittingButton: "Mengirim...",
    successTitle: "Terima kasih!",
    successMessage: "Konfirmasi dan ucapan Anda telah kami terima.",
    resetButton: "Kirim Tanggapan Lain",
    errorMessage: "Maaf, terjadi kesalahan. Silakan coba lagi.",
    notConfiguredMessage: "Formulir RSVP belum aktif. Silakan coba lagi nanti.",
  },
  wishes: {
    title: "Ucapan & Doa",
    subtitle: "Doa dan ucapan dari para tamu undangan",
    loadingMessage: "Memuat ucapan...",
    emptyMessage: "Belum ada ucapan. Jadilah yang pertama mengirimkan doa restu!",
    errorMessage: "Gagal memuat ucapan.",
    notConfiguredMessage: "Ucapan belum terhubung ke spreadsheet. Set APPS_SCRIPT_URL di .env.local, lalu restart server.",
    prevButton: "← Sebelumnya",
    nextButton: "Berikutnya →",
  },
  gallery: {
    title: "Gallery",
    subtitle: "Sepenggal cerita kami",
    prevButton: "Foto sebelumnya",
    nextButton: "Foto berikutnya",
  },
  gift: {
    title: "Wedding Gift",
    subtitle:
      "Kehadiran dan doa restu Anda sudah menjadi hadiah yang sangat berharga bagi kami. Apabila berkenan berbagi tanda kasih, informasi hadiah digital tersedia melalui tombol berikut.",
    accountNumberLabel: "Nomor Rekening",
    copyButton: "Salin",
    copiedButton: "Tersalin",
  },
  footer: {
    closing:
      "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.",
    signature: "Kami yang berbahagia,",
  },
};
